/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */
plugins {
    java
    antlr
}

dependencies {
    testImplementation("junit:junit:4.13.2")
    antlr("org.antlr:antlr4:4.9.3")
}

repositories {
    mavenCentral()
}

tasks.test {
    useJUnitPlatform()
}