name: Fool Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install java
        run: sudo apt install default-jdk -y

      - name: Download antlr4.9.3
        run: wget https://www.antlr.org/download/antlr-4.9.3-complete.jar -O antlr.jar

      - name: Generate SVM grammar
        run: java -jar antlr.jar src/svm/SVM.g4 -listener -visitor -Xexact-output-dir -o gen/svm

      - name: Generate FOOL grammar
        run: java -jar antlr.jar src/compiler/FOOL.g4 -listener -visitor -Xexact-output-dir -o gen/compiler
        
      - name: debug
        run: ls -R
      
      - name: Compiling java
        run: javac -cp antlr.jar $(find . -iname *.java)
      
      - name: Running Test
        run: java src/compiler/Test.class
