name: Fool Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install antlr
        run: sudo apt install antlr4 -y

      - name: Generate SVM grammar
        run: antlr4 src/svm/SVM.g4 -o gen

      - name: Generate FOOL grammar
        run: antlr4 src/compiler/FOOL.g4 -o gen
      
      - name: Compiling java
        run: javac -cp src -cp gen src/compiler/Test.java
      
      - name: Running Test
        run: java src/compiler/Test.class
