name: Fool Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install java
        run: sudo apt install default-jdk -y
        
      - name: Java version
        run: java --version
        
      - name: Javac version
        run: javac --version

      - name: Download antlr4.9.3
        run: wget https://www.antlr.org/download/antlr-4.9.3-complete.jar -O antlr.jar

      - name: Generate SVM grammar
        run: java -jar antlr.jar src/svm/SVM.g4 -listener -visitor -Xexact-output-dir -o src/svm

      - name: Generate FOOL grammar
        run: java -jar antlr.jar src/compiler/FOOL.g4 -listener -visitor -Xexact-output-dir -o src/compiler
        
      - name: debug
        run: tree .
      
      - name: debug
        run: find . -iname *.java
      
      - name: Compiling java
        run: javac -cp ".;antlr.jar" $(find ./src -iname *.java)
      
      - name: Running Test
        run: java src/compiler/Test.class
