name: Fool Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install java
        run: sudo apt install default-jdk -y

      - name: Download antlr
        run: wget https://www.antlr.org/download/antlr-4.9.3-complete.jar -O antlr.jar

      - name: Generate SVM grammar
        run: java -jar antlr.jar src/svm/SVM.g4 -o gen

      - name: Generate FOOL grammar
        run: java -jar antlr.jar src/compiler/FOOL.g4 -o gen
      
      - name: Compiling java
        run: javac -cp src src/compiler/Test.java
      
      - name: Running Test
        run: java src/compiler/Test.class
